### ISSUE TITLE
Problem compiling on CentOS / Fedora

### ISSUE THREAD

**Issue by guiditoito** [frgtn/rpcapd-linux#2]
It won't compile on Centos 6.5

  326  yum install wireshark
  327  yum search libpcap
  328  yum install libpcap libpcap-devel
  351  yum install flex
  354  yum search bison
  355  yum install bison bison-devel
  356  yum search bison
  359  yum install yacc
  360  yum search yacc
  361  yum install byacc
  368  yum install glibc-devel
  369  yum search libssl
  370  yum search ssl
  371  yum install openssl-devel
  372  yum provides libcrypt
  373  yum install libtool-ltdl-devel
  376  yum install glibc-static

~/rpcapd/rpcapd-linux# make
gcc -pthread -D_DEBUG -g -Wall -DHAVE_REMOTE -DHAVE_SNPRINTF -static -Ilibpcap/ -c rpcapd.c
gcc -pthread -D_DEBUG -g -Wall -DHAVE_REMOTE -DHAVE_SNPRINTF -static -Ilibpcap/ -c daemon.c
daemon.c: In function ‘daemon_AuthUserPwd’:
daemon.c:684: warning: implicit declaration of function ‘crypt’
daemon.c:684: warning: cast to pointer from integer of different size
daemon.c: In function ‘daemon_startcapture’:
daemon.c:1070: warning: pointer targets in passing argument 3 of ‘daemon_unpackapplyfilter’ differ in signedness
daemon.c:68: note: expected ‘int _’ but argument is of type ‘uint32 *’
daemon.c: In function ‘daemon_updatefilter’:
daemon.c:1270: warning: pointer targets in passing argument 3 of ‘daemon_unpackapplyfilter’ differ in signedness
daemon.c:1199: note: expected ‘int *’ but argument is of type ‘uint32 *’
gcc -pthread -D_DEBUG -g -Wall -DHAVE_REMOTE -DHAVE_SNPRINTF -static -Ilibpcap/ -c utils.c
gcc -pthread -D_DEBUG -g -Wall -DHAVE_REMOTE -DHAVE_SNPRINTF -static -Ilibpcap/ -c fileconf.c
gcc -pthread -D_DEBUG -g -Wall -DHAVE_REMOTE -DHAVE_SNPRINTF -static -Ilibpcap/ -c libpcap/pcap-remote.c
libpcap/pcap-remote.c: In function ‘pcap_read_nocb_remote’:
libpcap/pcap-remote.c:327: warning: pointer targets in passing argument 2 of ‘sock_recv’ differ in signedness
libpcap/sockutils.h:211: note: expected ‘char *’ but argument is of type ‘u_char *’
libpcap/pcap-remote.c: In function ‘pcap_startcapture_remote’:
libpcap/pcap-remote.c:1129: warning: pointer targets in passing argument 5 of ‘getsockopt’ differ in signedness
/usr/include/sys/socket.h:190: note: expected ‘socklen_t \* **restrict**’ but argument is of type ‘int *’
gcc -pthread -D_DEBUG -g -Wall -DHAVE_REMOTE -DHAVE_SNPRINTF -static -Ilibpcap/ -c libpcap/sockutils.c
gcc -pthread -D_DEBUG -g -Wall -DHAVE_REMOTE -DHAVE_SNPRINTF -static -Ilibpcap/ -c libpcap/pcap-new.c
gcc -pthread -D_DEBUG -g -Wall -DHAVE_REMOTE -DHAVE_SNPRINTF -static -Ilibpcap/ -o rpcapd rpcapd.o daemon.o utils.o fileconf.o pcap-remote.o sockutils.o pcap-new.o -Llibpcap/ -lpcap -lcrypt
daemon.o: In function `daemon_AuthUserPwd':
/root/rpcapd/rpcapd-linux/daemon.c:670: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
pcap-remote.o: In function`rpcap_remoteact_getsock':
/root/rpcapd/rpcapd-linux/libpcap/pcap-remote.c:2051: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libpthread.a(libpthread.o): In function `sem_open':
(.text+0x774d): warning: the use of`mktemp' is dangerous, better use `mkstemp'
daemon.o: In function`daemon_AuthUserPwd':
/root/rpcapd/rpcapd-linux/daemon.c:678: warning: Using 'getspnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
libpcap//libpcap.a(nametoaddr.o): In function `pcap_nametoaddr':
nametoaddr.c:(.text+0x475): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
libpcap//libpcap.a(nametoaddr.o): In function`pcap_nametonetaddr':
nametoaddr.c:(.text+0x405): warning: Using 'getnetbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
libpcap//libpcap.a(nametoaddr.o): In function `pcap_nametoproto':
nametoaddr.c:(.text+0x215): warning: Using 'getprotobyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
libpcap//libpcap.a(nametoaddr.o): In function`pcap_nametoport':
nametoaddr.c:(.text+0x259): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0xbb): undefined reference to`NSSLOW_Init'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0xd5): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0xe9): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0xfc): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x10e): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x121): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x12f): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x147): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x155): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x163): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x171): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x185): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x18d): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x1b0): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x1d9): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x1fc): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x215): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x21f): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x23a): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x2a3): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x2bb): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x2c3): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x2de): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x2ee): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x30c): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x322): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x33a): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x353): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x434): undefined reference to`NSSLOW_Shutdown'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x7ea): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(md5-crypt.o): In function `__md5_crypt_r':
(.text+0x834): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0xe2): undefined reference to`NSSLOW_Init'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0xff): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x113): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x12c): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x141): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x152): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x16e): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x183): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x195): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x1aa): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x1c2): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x1ce): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x208): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x23e): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x27c): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x294): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x2be): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x2c6): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x2d7): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x2ef): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x331): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x368): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x374): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x406): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x41a): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x44a): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x480): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x488): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x532): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x59e): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x5b6): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x5be): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x5dc): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x5f0): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x612): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x62a): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x642): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x661): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0x6d9): undefined reference to`NSSLOW_Shutdown'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0xef2): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0xf28): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0xf34): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha256-crypt.o): In function `__sha256_crypt_r':
(.text+0xf55): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0xf1): undefined reference to`NSSLOW_Init'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x10e): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x122): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x13b): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x154): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x165): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x17d): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x18e): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x19f): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x1b0): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x1c4): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x1cc): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x1f8): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x227): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x254): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x26d): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x28d): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x295): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x2a6): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x2ba): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x2ea): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x319): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x321): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x3d2): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x3e9): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x409): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x435): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x43d): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x512): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x57e): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x596): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x59e): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x5bc): undefined reference to`NSSLOWHASH_NewContext'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x5d0): undefined reference to`NSSLOWHASH_Begin'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x5f2): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x60a): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x622): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x641): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x6c9): undefined reference to`NSSLOW_Shutdown'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x14ff): undefined reference to`NSSLOWHASH_Update'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x1537): undefined reference to`NSSLOWHASH_End'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x153f): undefined reference to`NSSLOWHASH_Destroy'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libcrypt.a(sha512-crypt.o): In function `__sha512_crypt_r':
(.text+0x1568): undefined reference to`NSSLOWHASH_Destroy'
collect2: ld returned 1 exit status
make: *_\* [rpcapd] Error 1

**Comment by truatpasteurdotfr** [comment]
just for your info: https://bugzilla.redhat.com/show_bug.cgi?id=1284089

**Comment by vtsingaras** [comment]
It compiles successfully when using dynamic linking instead of static by removing '-static' from the Makefile. Tested on CentOS6.8 .

**Comment by frgtn** [comment]
Cool, thanks for checking!
